### ISSUE TITLE
IOS 12

### ISSUE THREAD

**Issue by chmondkind** [alexrestrepo/KZColorPicker#10]
Hi
Will the color picker compile on IOS12? if not - hints appreciated 
Thanks

**Comment by alexrestrepo** [comment]
Hi there, I haven't touched this code in a loooong time, so idk if it compiles anymore... and most likely you'd need to convert it to ARC as well. It shouldn't be too hard to get it to work, but I'd recommend using something more up-to-date such as: https://noahgilmore.com/blog/cifilter-colorwheel/

Alex.

**Comment by chmondkind** [comment]
Hi
Thank you very much for your low latency and the recommendation!
Cheers

mk

**Comment by chmondkind** [comment]
Hi
Thank you very much for your low latency and the recommendation!
Cheers

mk
