### ISSUE TITLE
How can I adjust y position of KZColorPickerBrightnessSlider?

### ISSUE THREAD

**Issue by iraj-wisilica** [alexrestrepo/KZColorPicker#9]
I am trying to modify the y position of the brightness slider. I have modified KZColorPickerBrightnessSlider *slider = [[KZColorPickerBrightnessSlider alloc] initWithFrame:CGRectMake(24,277,272,38) but It remains in the same position.

**Comment by alexrestrepo** [comment]
The location is fixed in -LayoutSubviews, Take a look at 
- (void) fixLocations;

In KZColorPicker.m

**Comment by iraj-wisilica** [comment]
Thank you. I will look into it.

**Comment by iraj-wisilica** [comment]
It works like a charm
